### ISSUE TITLE
init of StandardControlReact order

### ISSUE THREAD

**Issue by strwase** [scottdurow/pcf-react#2]
Hi Scott, 

My ViewModel needs to call the DataVerse API in the onLoad event using some of the input params.
However, in the StandardControlReact class, the context is initialized after the ServiceProvider, meaning the onLoad event of my ViewModel throws a `this.controlContext is undefined error`.

If you switch the order of these 2 lines, everything works fine (I'm doing it manually each time for now :-) )

![image](https://user-images.githubusercontent.com/10077785/125609390-b0cb5ac7-7124-4b8f-810a-6c8ec09ec3ef.png)

Any chance you could update this in the source itself?

Regards.

**Comment by scottdurow** [comment]
This project is now archived.
