### ISSUE TITLE
StandardControlReact >> VirtualControlReact

### ISSUE THREAD

**Issue by DeLaSog** [scottdurow/pcf-react#9]
Hi Scott,

From what I understand the StandardControlReact does not support the use of Virtual Type coded components (the name kinda hints this), as the UpdateView() method in StandardControlReact is only for standard types.

Is there a way to implement StandardControlReact so that it can be used with Virtual Type coded components? Or is the only way to use Virtual Type components, is to edit the UpdateView() in a class that implements the ComponentFramework?ReactControl class?

Thanks

**Comment by scottdurow** [comment]
This project is now archived.
